name: prodxcloud.io Build and Deploy

on:
  push:
    branches:
      - prod
      - main

env:
  ENVIRONMENT: ${{ github.ref_name }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}  

jobs:
  build:
    name: Build the UI and Deploy to AWS PROD EC2
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force

      - name: Build the React application
        run: npm run build
      - name: Prepare EC2 prod_contents Folder
        env:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.PRIVATE_KEY}}
        run: |
          echo "${PRIVATE_KEY}" > PK && chmod 600 PK   
          ssh -o StrictHostKeyChecking=no -i "./PK" ${REMOTE_USER}@${REMOTE_HOST} '
            rm -rf prod_contents && mkdir -vp prod_contents
            '    
      - name: SCP ( COPY ) to EC2 prod_contents
        env:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.PRIVATE_KEY}}
        run: |
          scp -o StrictHostKeyChecking=no -i "./PK" -r ./dist ${REMOTE_USER}@${REMOTE_HOST}:~/prod_contents
         
      - name: Copy prod_contents to nginx public directory
        env:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.PRIVATE_KEY}}
        run: |
          echo "${PRIVATE_KEY}" > PK && chmod 600 PK            
          ssh -o StrictHostKeyChecking=no -i "./PK" ${REMOTE_USER}@${REMOTE_HOST} '
            cd prod_contents/dist && sudo cp -rf * /usr/share/nginx/html/
            '
